# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/robot_id_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

import robot_id_pb2 as api_dot_robot__id__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='api/robot_id_service.proto',
  package='bosdyn.api',
  syntax='proto3',
  serialized_options=b'B\023RobotIdServiceProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1a\x61pi/robot_id_service.proto\x12\nbosdyn.api\x1a\x12\x61pi/robot_id.proto2Y\n\x0eRobotIdService\x12G\n\nGetRobotId\x12\x1a.bosdyn.api.RobotIdRequest\x1a\x1b.bosdyn.api.RobotIdResponse\"\x00\x42\x15\x42\x13RobotIdServiceProtob\x06proto3'
  ,
  dependencies=[api_dot_robot__id__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_ROBOTIDSERVICE = _descriptor.ServiceDescriptor(
  name='RobotIdService',
  full_name='bosdyn.api.RobotIdService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=62,
  serialized_end=151,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetRobotId',
    full_name='bosdyn.api.RobotIdService.GetRobotId',
    index=0,
    containing_service=None,
    input_type=api_dot_robot__id__pb2._ROBOTIDREQUEST,
    output_type=api_dot_robot__id__pb2._ROBOTIDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROBOTIDSERVICE)

DESCRIPTOR.services_by_name['RobotIdService'] = _ROBOTIDSERVICE

# @@protoc_insertion_point(module_scope)
